# Site
name: "NooSync"
title: "NooSync"
description: "Hey, we are NooSync! We craft tech solutions to support startups and established businesses to achieve their goals."
logo: 'assets/images/noosync_logo_v2.png'
favicon: 'assets/images/noosync_logo_favicon_v1.png'
#baseurl: /noosync
#google_analytics: 'UA-xxxxxxxx-1'
#disqus: ''
#mailchimp-list: 
include: ["_pages"]
permalink: /:path/:title/
email: hello@noosync.com

#Languages
languages:
  en:
    label: English
    icon: assets/images/flag-en.png
  pt-BR:
    label: PortuguÃªs
    icon: assets/images/flag-pt-BR.png

# Authors
authors:
  foss:
    name: Marcelo Foss
    display_name: Marcelo Foss
    avatar: 'assets/images/foss.png'
    email: ""
    web: ""
    twitter: ""
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
